name: Tests (PHP)

on: [push, pull_request]

jobs:
    tests:
        name: P${{ matrix.php }} - ${{ matrix.dependency-version }}
        strategy:
          fail-fast: true
          matrix:
            php: [7.4, 7.3]
            os: [ ubuntu-latest ]
            dependency-version: [prefer-stable]

        runs-on: ${{ matrix.os }}

        env:
          DB_DATABASE: scout_testing
          DB_USER: root
          DB_PASSWORD: root
          DB_PORT: 3306
          DB_DRIVER: mysql

        steps:
            - uses: actions/checkout@v2

            - name: Set up MySQL
              run: |
                sudo /etc/init.d/mysql start
                mysql -e 'CREATE DATABASE ${{ env.DB_DATABASE }};' -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }}

            - name: Setup cache environment
              id: cache-env
              uses: shivammathur/cache-extensions@v1
              with:
                php-version: ${{ matrix.php }}
                extensions: mbstring,dom,fileinfo,mysql,imagick,bcmath,pcntl,zip,soap,intl,gd,exif,iconv
                key: extensions

            - uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  extensions: mbstring,dom,fileinfo,mysql,imagick,bcmath,pcntl,zip,soap,intl,gd,exif,iconv
                  coverage: none

            - name: Install dependencies
              run: |
                  composer update --${{ matrix.dependency-version }} --prefer-dist --no-interaction --no-suggest

            - name: Run tests
              run: ./vendor/bin/codecept run unit
              env:
                  APP_ENV: testing
